CXX = g++
CPPFLAGS = -I ../
CXXFLAGS = -std=c++11

OBJ = \
	  AUC.o \
	  CAN.o \
	  CHB.o \
	  MAN.o \
	  MIN.o

all: $(OBJ)

clean:
	rm -f $(OBJ)

AUC.o: AUC.h

CAN.o: CAN.h

CHB.o: CHB.h

MAN.o: MAN.h

MIN.o: MIN.h
